--- 
abstract: Track loaded modules and namespaces
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
  Test::Script: 1.02
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Leak-Module
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.005
version: 0.01_02
