---
abstract: 'Track loaded modules and namespaces'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.47
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Leak-Module
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Devel-Leak-Module
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Devel-Leak-Module
version: 0.02
